version: '3.8'

services:
  app:
    build: .
    ports:
      # The host port is set from the PORT environment variable, defaulting to 8000.
      # The container port is fixed at 8000.
      - "${PORT:-8000}:8000"
    env_file:
      - .env
