GEMINI_MODEL="gemini-2.5-flash"
GEMINI_FALLBACK_MODEL="gemini-1.5-flash"
TIPO_DE_INTERACCION_MESSAGES_UNTIL_HUMAN=4
MESSAGES_AFTER_CONVERSATION_FINISHED=3
CLIENTE_ACTIVO_MESSAGES_UNTIL_HUMAN = 5
ADMON_MESSAGES_UNTIL_HUMAN = 5
TRANSPORTISTA_MESSAGES_UNTIL_HUMAN = 5
CLASSIFICATION_THRESHOLD = 0.85
