from enum import Enum


class InteractionType(str, Enum):
    USER = "user"
    MODEL = "model"
    TOOL = "tool"


class CategoriaClasificacion(str, Enum):
    CLIENTE_POTENCIAL = "CLIENTE_POTENCIAL"
    CLIENTE_ACTIVO = "CLIENTE_ACTIVO"
    TRANSPORTISTA_TERCERO = "TRANSPORTISTA_TERCERO"
    PROVEEDOR_POTENCIAL = "PROVEEDOR_POTENCIAL"
    USUARIO_ADMINISTRATIVO = "USUARIO_ADMINISTRATIVO"
    CANDIDATO_A_EMPLEO = "CANDIDATO_A_EMPLEO"
    OTRO = "OTRO"


class TipoDeServicio(str, Enum):
    IMPORTACION = "IMPORTACION"
    EXPORTACION = "EXPORTACION"
    DISTRIBUCION = "DISTRIBUCION"
    ALMACENAMIENTO = "ALMACENAMIENTO"
    NACIONAL = "NACIONAL"
    ANDINO = "ANDINO"
    ITR = "ITR"  # Recibo de Traslado de Intercambio


class MotivoDeDescarte(str, Enum):
    RUTA_FUERA_DE_COBERTURA = "RUTA FUERA DE COBERTURA"
    PRODUCTO_NO_VALIDO = "PRODUCTO/MERCANCIA  NO TRANSPORTADA POR BSSL"
    SERVICIO_NO_PRESTADO = "SERVICIO NO PRESTADO POR BSSL"


class CategoriaClienteActivo(str, Enum):
    TRAZABILIDAD = "TRAZABILIDAD"
    BLOQUEOS_CARTERA = "BLOQUEOS_CARTERA"
    FACTURACION = "FACTURACION"
    COTIZACION = "COTIZACION"
    OTRO = "OTRO"


class CategoriaUsuarioAdministrativo(str, Enum):
    RETEFUENTE = "RETEFUENTE"
    CERTIFICADO_LABORAL = "CERTIFICADO_LABORAL"
    OTRO = "OTRO"


class CategoriaTransportista(str, Enum):
    MANIFIESTOS = "MANIFIESTOS"
    ENTURNAMIENTOS = "ENTURNAMIENTOS"
    APP_CONDUCTORES = "APP_CONDUCTORES"
    OTRO = "OTRO"

